config/routes.rb
Pricer::Application.routes.draw do

  resources :products do
    member do
      post :tag
      post :untag
    end
  end

  resources :tags do 
    collection do
      get :autocomplete
      get :my
    end
  end

  resources :categories do
    resources :params
  end

  

  get "home/index"

  root :to => 'home#index'

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :params

  has_many :products

  acts_as_tagger

end

app/models/param.rb
class Param < ActiveRecord::Base
  belongs_to :category
end

app/models/product.rb
class Product < ActiveRecord::Base
  belongs_to :category

  acts_as_taggable
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @categories }
    end
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
    @category = Category.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @category }
    end
  end

  # GET /categories/new
  # GET /categories/new.json
  def new
    @category = Category.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @category }
    end
  end

  # GET /categories/1/edit
  def edit
    @category = Category.find(params[:id])
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(params[:category])

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render json: @category, status: :created, location: @category }
      else
        format.html { render action: "new" }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /categories/1
  # PUT /categories/1.json
  def update
    @category = Category.find(params[:id])

    respond_to do |format|
      if @category.update_attributes(params[:category])
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category = Category.find(params[:id])
    @category.destroy

    respond_to do |format|
      format.html { redirect_to categories_url }
      format.json { head :ok }
    end
  end
end

app/controllers/params_controller.rb
class ParamsController < ApplicationController
  # GET /params
  # GET /params.json
  def index
    @params = Param.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @params }
    end
  end

  # GET /params/1
  # GET /params/1.json
  def show
    @param = Param.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @param }
    end
  end

  # GET /params/new
  # GET /params/new.json
  def new
    @param = Param.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @param }
    end
  end

  # GET /params/1/edit
  def edit
    @param = Param.find(params[:id])
  end

  # POST /params
  # POST /params.json
  def create
    @param = Param.new(params[:param])

    respond_to do |format|
      if @param.save
        format.html { redirect_to @param, notice: 'Param was successfully created.' }
        format.json { render json: @param, status: :created, location: @param }
      else
        format.html { render action: "new" }
        format.json { render json: @param.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /params/1
  # PUT /params/1.json
  def update
    @param = Param.find(params[:id])

    respond_to do |format|
      if @param.update_attributes(params[:param])
        format.html { redirect_to @param, notice: 'Param was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @param.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /params/1
  # DELETE /params/1.json
  def destroy
    @param = Param.find(params[:id])
    @param.destroy

    respond_to do |format|
      format.html { redirect_to params_url }
      format.json { head :ok }
    end
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController


  def tag
    @product = Product.find params[:id]
    context = params[:context].to_sym
    new_tags = @product.tag_list_on(context).push(params[:tag])
    @product.category.tag(@product, :with => new_tags, :on => context)
    @product.save
    render :text=>nil
  end

  def untag
    @product = Product.find params[:id]
    context = params[:context].to_sym
    new_tags = @product.tag_list_on(context)
    new_tags.delete(params[:tag])
    @product.set_tag_list_on(context, new_tags)
    @product.category.tag(@product, :with => new_tags, :on => context)
    @product.save
    render :text=>nil
  end

  # GET /products
  # GET /products.json
  def index
    @products = Product.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @products }
    end
  end

  # GET /products/1
  # GET /products/1.json
  def show
    @product = Product.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @product }
    end
  end

  # GET /products/new
  # GET /products/new.json
  def new
    @product = Product.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @product }
    end
  end

  # GET /products/1/edit
  def edit
    @product = Product.find(params[:id])
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(params[:product])

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render json: @product, status: :created, location: @product }
      else
        format.html { render action: "new" }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /products/1
  # PUT /products/1.json
  def update
    @product = Product.find(params[:id])

    respond_to do |format|
      if @product.update_attributes(params[:product])
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product = Product.find(params[:id])
    @product.destroy

    respond_to do |format|
      format.html { redirect_to products_url }
      format.json { head :ok }
    end
  end
end

app/controllers/tags_controller.rb
# -*- encoding : utf-8 -*-
class TagsController < ApplicationController
  def autocomplete
    q = "%#{params[:term]}%"


    @tags = ActsAsTaggableOn::Tag.includes(:taggings).where("taggings.tagger_id = ? and taggings.context = ?", 
    params[:category], params[:context]).where("name like ?", q)

    respond_to do |format|
        format.js do
          render :inline => @tags.to_json
        end
     end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/params_helper.rb
module ParamsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/categories/_form.html.erb
<%= simple_form_for(@category) do |f| %>
  <%= f.error_notification %>

  <div class="inputs">

    <%= f.input :name %>

    <%= f.input :group_id %>

  </div>

  <div class="actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing category</h1>

<%= render 'form' %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<h1>Listing categories</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Group</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @categories.each do |category| %>
  <tr>
    <td><%= category.name %></td>
    <td><%= category.group_id %></td>
    <td><%= link_to 'Show', category %></td>
    <td><%= link_to 'Edit', edit_category_path(category) %></td>
    <td><%= link_to 'Destroy', category, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Category', new_category_path %>

app/views/categories/new.html.erb
<h1>New category</h1>

<%= render 'form' %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @category.name %>
</p>

<p>
  <b>Group:</b>
  <%= @category.group_id %>
</p>


<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Pricer</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

    <!--Header starts here -->
    <div id="header">
    
        
    </div>
    <!-- header ends here -->
    
    <!-- main content starts here-->
    <div class="wrapper">
        <%= yield %>
    </div>
    <!-- main content ends here-->

</body>
</html>

app/views/params/_form.html.erb
<%= simple_form_for(@param) do |f| %>
  <%= f.error_notification %>

  <div class="inputs">

    <%= f.input :name %>

    <%= f.input :category_id %>

  </div>

  <div class="actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/params/edit.html.erb
<h1>Editing param</h1>

<%= render 'form' %>

<%= link_to 'Show', @param %> |
<%= link_to 'Back', params_path %>

app/views/params/index.html.erb
<h1>Listing params</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Category</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @params.each do |param| %>
  <tr>
    <td><%= param.name %></td>
    <td><%= param.category_id %></td>
    <td><%= link_to 'Show', param %></td>
    <td><%= link_to 'Edit', edit_param_path(param) %></td>
    <td><%= link_to 'Destroy', param, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Param', new_param_path %>

app/views/params/new.html.erb
<h1>New param</h1>

<%= render 'form' %>

<%= link_to 'Back', params_path %>

app/views/params/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @param.name %>
</p>

<p>
  <b>Category:</b>
  <%= @param.category_id %>
</p>


<%= link_to 'Edit', edit_param_path(@param) %> |
<%= link_to 'Back', params_path %>

app/views/products/_form.html.erb
<%= simple_form_for(@product) do |f| %>
  <%= f.error_notification %>

  <div class="inputs">

    <%= f.input :name %>

    <%= f.input :category_id %>


  </div>

  <div class="actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing product</h1>

<%= render 'form' %>



<%-@product.category.params.each do |p|%>

<%=p.name%>

<ul id="tags_<%=p.name%>">
  <%@product.tag_list_on(p.name.to_sym).each do |t|%>
   <li>
     <%=t%>
   </li>
  <%end%>
</ul>


<script type="text/javascript">
var tags = [<%=raw @product.tag_list_on(p.name.to_sym).collect{|el| "\"#{el}\""}.join(",")%>];
    $(document).ready(function() {
        $("#tags_<%=p.name%>").tagit({
          removeConfirmation: true,
          allowSpaces: true,
          onTagAdded: function(event, tag) {
            var t = $("span", tag)[0].innerText;
            if ($.inArray(t, tags)>0){
              return;
            }else{
              $.post("<%=tag_product_path(@product, :context=>p.name)%>", {tag: t});
            }
          },
          onTagRemoved: function(event, tag) {
              var t = $("span", tag)[0].innerText;
               $.post("<%=untag_product_path(@product, :context=>p.name)%>", {tag: t});
          },
          tagSource: function( request, response ) {
            //console.log("1");
            $.ajax({
                url: "/tags/autocomplete", 
                data: { term:request.term, category:'<%=@product.category_id%>', context:'<%=p.name%>' },
                dataType: "json",
                success: function( data ) {
                  response( $.map( data, function( item ) {
                      return {label: item.name, value: item.name}
                     }
                    )
                   );
                }
              });
          }
          })
    });  
</script>



<br/><br/>

<%end%>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<h1>Listing products</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Category</th>
    <th>Description</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @products.each do |product| %>
  <tr>
    <td><%= product.name %></td>
    <td><%= product.category_id %></td>
    <td><%= product.description %></td>
    <td><%= link_to 'Show', product %></td>
    <td><%= link_to 'Edit', edit_product_path(product) %></td>
    <td><%= link_to 'Destroy', product, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Product', new_product_path %>

app/views/products/new.html.erb
<h1>New product</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @product.name %>
</p>

<p>
  <b>Category:</b>
  <%= @product.category_id %>
</p>

<p>
  <b>Description:</b>
  <%= @product.description %>
</p>


<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>